### ISSUE TITLE
[Bug Report] Improve the rotation of the whole Mpet

### ISSUE THREAD

**Issue by LordRazen** [miniaturepets/issues#242]
# Bug Report

### Technical Information
Same as always ^^
- Server Software: Paper version git-Paper-288 (MC 1.16.4)
- Plugin Version: v2.5.6
- Dump File: https://pastebin.com/VXRzUk0d

### General Information
**Bug Description**
You might have recognized there's a slight difference between the blocks while the model is rotated. 
![Unbenannt](https://user-images.githubusercontent.com/9381368/112003006-c7aab580-8b20-11eb-84f8-14a41f377827.png)

You might say "that's just Minecraft", it's not possible to be more accurate. 

Well, it is. I faced the same issue while writing the datapack generator for Minecraft-Heads.com. We actually found out, that Minecraft armorstands only have 256 different positions to show 360°. 
So if you calculate this: 360 / 256 = 1.40625° 

So, if you try to rotate the model for 2°, there're those problems since the armorstands are only rotated 1.40625°. 

Now if you wonder when which position is taken:
From 0° to 1.40624, the 0° position is used.
From 1.40625° to 2.8125°, the 1.40625° is taken and so on. 

So, with all this, how can you fix this bug: Simple. If you calculate the rotation, only allow rotations with an angle which is a multiple of the value 1.40625°. Do not allow other values like 1° or 2°. This will solve the rotation issues.

**Comment by danielnaaman** [comment]
Hi, this is impossible, at least from my understanding of Minecraft, some of these things depend purely on packet loss, client side processing, and tons of factors we can't determine.

Since a Miniature Pet is made out of blocks (or entities for that matter), we can't exactly make all the blocks move at the exactly same time and still have the client see that. My best example for this would be how The Flash runs so fast that you can only see him as a streak. 
![image](https://user-images.githubusercontent.com/16944217/114076257-2311cd00-98af-11eb-81d9-723f6f138351.png)

**Comment by LordRazen** [comment]
Erm, you got me wrong. This issue is not about moving all armorstands in the exact time. 

It's about very tiny misscalculations in the positionings of the armorstands due to the fact, that Minecraft can only render armorstand rotations which are a multiple of 360/256. 

I had the exact same bug from the images inside the Minecraft Heads Datapacks Generator and could fix it. If I can do this, we can do this for the plugin, too ^^

**Comment by danielnaaman** [comment]
Done
