### ISSUE TITLE
[Feature Request] Improve default Config

### ISSUE THREAD

**Issue by LordRazen** [miniaturepets/issues#245]
# Feature Request
I recommend to set this setting to true in the default config:
`bypassSpawnProtections: false`

Reason: It helps solving issues with the plugin, and this is always good for the first installation.

**Comment by danielnaaman** [comment]
Hey @LordRazen ,
Can you explain and give examples of how this will improve the experience of using the plugin?

Daniel

**Comment by LordRazen** [comment]
Well, it can disable the pet spawn while somebody starts the plugin the first time. 

And we already got Worldguard as an issue here, even if you clearly state the WG problem in the log. 

But if Worldguard is setup correctly and the plugin still dont work cause of this setting, the user might get the intention the plugin is buggy cause it doesnt work out of the box. 

We should avoid whatever could raise such a feeling.

**Comment by danielnaaman** [comment]
We've decided that we shouldn't implement this feature. Allow me to explain why.

Technically speaking, the feature is meant so that if a given plugin overrides the spawn of a pet, you can enable this feature to obtain a "double override" from our side, meaning that we will override the override so the pet will spawn properly.

Having that said, under most scenarios (that we've seen so far) Miniature Pets works just fine on almost any environment. This should be a last resort, not a default. From my understanding, it's kind of a "hack" and not a best practice. Just in case it's needed, we've added it.
