### ISSUE TITLE
[Feature Request] Banner Patterns

### ISSUE THREAD

**Issue by LordRazen** [miniaturepets/issues#248]
# Feature Request
The idea is easy: If banner patterns would be supported, there could be a lot more fancy pets ^^

I didnt find any pets with banner patterns yet, if the feature exists already a documentation would be great :-)

**Comment by danielnaaman** [comment]
Hi, I think you are correct and this is yet to be implemented.

I think it's a great suggestion and I'll add it to backlog and not set a version for it yet, since we have a few others things to get done first. I assume we can see such functionality in 3-4 months? I think it wouldn't be bet specific though, more something like being able to add a banner to your pet.

We'll see

**Comment by liorsl** [comment]
Hello,
That's a very nice idea and it will be available in the next release.
You will have to set the item material to one of the valid types of banners like you would for any other item, then add a section called `patterns` to the item properties. Bellow is a quick example I used for testing:
```yaml
banner:
  Material: BLACK_BANNER
  patterns:
  - color: RED
    pattern: SQUARE_TOP_RIGHT
```
You can add as many patterns as you want. 

Have a nice day!
