### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by ArnoPompio** [MiniaturePets/Issues#255]
# Bug Report

### Technical Information
* Server Software: PaperMC 1.16.5 700
* Plugin Version:  2.5.7
* Dump File: https://pastebin.com/unXkni9U

### General Information

**Bug Description**
We are able to rename pets with ShowItem plugin (%item%). It makes the players crash.

**Instructions To Produce**
1. Grab out a pet from the pet plugin
2. Rename said pet
3. When it asks for the name in chat, respond with [i] (%item%)
4. Your pet will now be named something like $showitem-93310533$
5. Use this name in places that may be seen in chat. Even places they normally can not be!

**Visual Demonstration**
Original report :
![1](https://user-images.githubusercontent.com/70692501/118789402-0ba60680-b895-11eb-901f-ecab87f727c8.png)
![2](https://user-images.githubusercontent.com/70692501/118789406-0c3e9d00-b895-11eb-969f-7d63c6ff759f.png)

**Comment by DanielNaaman** [comment]
Hey,
That surely seems like a bug!

We're on it
- Daniel

**Comment by liorsl** [comment]
Hello,
Thanks for the report, definitely an interesting one.
Its worth noting this problem is built from 2 parts:
- MiniaturePets accepting placeholder use of 3rd party plugins when choosing pet names
- The item display plugin's developer didn't consider this edge case, which causes the client to crash. 
I suggest you bring this to the attention of your plugin developer.
Anyway, the first part will be fixed in the next version so you should not face that problem again.
