### ISSUE TITLE
respawn pet when falling to void

### ISSUE THREAD

**Issue by PandaKeny** [MiniaturePets/Issues#263]
When pet falls to void pet will have time to respawn itself

**Comment by DanielNaaman** [comment]
Please elaborate

**Comment by UltraFaceguy** [comment]
I talked with him on discord, the issue seems to be that in some cases, your pet can be destroyed (in this case, falling into the void). When this occurs, the /pet call command fails, as technically, the pet no longer exists. The request is that /pet call instead of sending an error, just respawns the pet and places it near the user, pretending as if the destruction never happened. 

I imagine this would be useful for when the user doesn't know that the pet was destroyed by... something, or, just as a nice quality of life feature

**Comment by DanielNaaman** [comment]
I believe we should fix this in two ways:
1) When a player dies, the pet will automatically respawn next to him (configurable in config.yml)
2) fix /pet call

Will be done in next version.
@liorsl

**Comment by liorsl** [comment]
Hello,
Thanks for bringing this up to our attention.
This problem will be resolved in the next version.
