### ISSUE TITLE
[Bug Report] error on startup

### ISSUE THREAD

**Issue by haroldrc** [MiniaturePets/Issues#316]
# Bug Report

### Technical Information
* Server Software: linux
* Plugin Version:  2.7.3
* Dump File:  https://pastebin.com/TPAsmwfL
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
- https://pastebin.com/PUbv3YsG
- i get this error when starting the server and when someone does / pet

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. use pterodactyl
2. share the plugin config folder with other servers via pterodactyl mount
3. 
4. 

**Logs**

**Visual Demonstration**
If you have any images or videos of the bug, you can post them here. Try to use services like YouTube or Imgur and not upload it to your own servers.

**Comment by Aurillium** [comment]
Hello! From the error you're getting in the console and from what I can see about Pterodactyl mounts, have you checked that your mount isn't read-only?
MiniaturePets needs to be able to make changes to the config file sometimes as well as read it, and what the error is telling us is that it's not able to do this because the file system (your mount) is read-only
Can I ask what the purpose of using a Pterodactyl mount is in this case? If you can tell me I should be able to guide you through fixing it because it's unfortunately not as simple as just switching off read-only

**Comment by GC-spigot** [comment]
You need to chmod or change permissions of your files ^
