### ISSUE TITLE
Miniature pets system

### ISSUE THREAD

**Issue by jugandomiguel** [MiniaturePets/Issues#319]
Hi, I want to ask if this use custom models because I want to use this with GeyserMC (Bedrock Support)  
But bedrock can't load custom models. 
Please any help

**Comment by Awpmeister2170** [comment]
The plugin uses Armorstands / PlayerHeads etc for Pets and with that it can cause Limitations with Bedrock which im afraid there is not alot we can do.

**Comment by jugandomiguel** [comment]
mmm wdym limitations?
but if this plugin use custommodels I can't buy it

**Comment by jugandomiguel** [comment]
But if only use armor stands and heads don't make trouble with bedrock users

**Comment by jugandomiguel** [comment]
and this website don't load https://hub.miniaturepets.net/marketplace/

**Comment by Awpmeister2170** [comment]
The plugin doesnt require any Custom Models / resoursepacks etc ( Pets are made up of only Armorstands and Heads that you can get from minecraftheads for example 

Bedrock can cause Limitations with the Armor stands etc sometimes Bedrock players dont see the Pets fully.

People can make Pets using Blockbench / Modelengine if they want to but it isnt needed.

The Marketplace is currently down because we are moving it all to a new location but if you have the Plugin and are wanting to purchase additional pets from Creators you can DM me on Discord after Verifying your Account using our Discord Verification System.

If you have anymore questions please head on over to the Discord as this Github is for Issues / Suggestions Prepurchase and support is in the Discord :) https://discord.gg/pzkt3TZM

**Comment by jugandomiguel** [comment]
Thanks
